version: "3.8"

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_SECRET_ACCESS_KEY="FAKE"
      - AWS_ACCESS_KEY_ID="FAKE"
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./docker/config/aws-init.sh:/etc/localstack/init/ready.d/aws-init.sh"

  redis:
    container_name: "redis"
    image: redis:latest
    ports:
      - "6379:6379"

  prometheus:
    container_name: "prometheus"
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./docker/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro"

  grafana:
    container_name: "grafana"
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
        - "./docker/data/grafana:/var/lib/grafana"